ARG BASE_IMAGE=rocm/pytorch:rocm6.4.1_ubuntu24.04_py3.12_pytorch_release_2.6.0
#ARG BASE_IMAGE=rocm/pytorch:rocm6.4.1_ubuntu24.04_py3.12_pytorch_release_2.7.1
#ARG BASE_IMAGE=rocm/pytorch:rocm6.4.1_ubuntu24.04_py3.12_pytorch_release_2.5.1
#ARG BASE_IMAGE=rocm/pytorch:rocm6.4.1_ubuntu24.04_py3.12_pytorch_release_2.4.1
FROM ${BASE_IMAGE}

ARG ARG_CONDA_ENV=py_3.12
#ARG_RAY_COMMIT_HASH must be "latest" or "master/{COMMIT_HASH}"
ARG ARG_RAY_COMMIT_HASH=latest
ENV RAY_INSTALL_CMD="ray[all] @ https://s3-us-west-2.amazonaws.com/ray-wheels/${ARG_RAY_COMMIT_HASH}/ray-3.0.0.dev0-cp312-cp312-manylinux2014_x86_64.whl"

ENV CONDA_DEFAULT_ENV=${ARG_CONDA_ENV}
ENV PATH="/opt/conda/envs/${ARG_CONDA_ENV}/bin:$PATH"
ENV CONDA_PREFIX="/opt/conda/envs/${ARG_CONDA_ENV}"

# Switch to bash shell for all RUN commands
SHELL ["/bin/bash", "-c"]

# System dependencies
RUN apt update && apt install -y build-essential python3-dev clang-format-15 amd-smi-lib

# Initialize and activate Conda in bash shell
RUN conda init && \
    eval "$(conda shell.bash hook)" && \
    conda activate ${ARG_CONDA_ENV} && \
    pip install -U "ray[all] @ https://s3-us-west-2.amazonaws.com/ray-wheels/${ARG_RAY_COMMIT_HASH}/ray-3.0.0.dev0-cp312-cp312-manylinux2014_x86_64.whl"&& \
    pip install --upgrade pip && \
    pip install transformers openai vllm

